name: Node.js Build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
           node-version: '18.x'
           cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
